/** @type {import('jest').Config} */
module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  roots: ['<rootDir>/test'],
  testMatch: ['<rootDir>/test/**/*.test.ts'],
  transform: {
    '^.+\\.(t|j)s$': [
      'ts-jest',
      {
        tsconfig: '<rootDir>/tsconfig.spec.json',
      },
    ],
  },
  testEnvironment: 'node',
  clearMocks: true,
  coverageProvider: 'v8',
  collectCoverage: true,
  collectCoverageFrom: [
    '<rootDir>/src/configuration/assert-jira-triage-runtime-ready.ts',
    '<rootDir>/src/configuration/assert-repository-review-runtime-ready.ts',
    '<rootDir>/src/configuration/node-configuration.ts',
    '<rootDir>/src/agent/provider/node-agent-llm-resolver.ts',
    '<rootDir>/src/agent/provider/error/error.ts',
    '<rootDir>/src/agent/agent.module.ts',
    '<rootDir>/src/error/error.ts',
    '<rootDir>/src/agent/agent-process-resolver.ts',
    '<rootDir>/src/handlers/jira-triage/mapper/jira-triage-classification-mapper.ts',
    '<rootDir>/src/handlers/jira-triage/composer/jira-triage-prompt-composer.ts',
    '<rootDir>/src/handlers/repository-review/composer/repository-review-prompt-composer.ts',
    '<rootDir>/src/handlers/repository-review/mapper/repository-review-result-mapper.ts',
    '<rootDir>/src/execution/handler/execution-job-handler-registry.ts',
    '<rootDir>/src/execution/handler/error/error.ts',
    '<rootDir>/src/execution/jobs/processing/execution-job-processor.ts',
    '<rootDir>/src/execution/jobs/polling/execution-job-poller.ts',
    '<rootDir>/src/cortex/cortex-client.ts',
    '<rootDir>/src/cortex/cortex-request.ts',
    '<rootDir>/src/cortex/resources/execution-job/cortex-execution-job-resource.ts',
    '<rootDir>/src/cortex/resources/execution-job/error/error.ts',
    '<rootDir>/src/cortex/resources/node/cortex-node-resource.ts',
    '<rootDir>/src/cortex/resources/node/error/error.ts',
    '<rootDir>/src/node/node-descriptor.provider.ts',
    '<rootDir>/src/workspace/git-workspace-manager.ts',
  ],

  coverageDirectory: '<rootDir>/coverage',
  coverageReporters: ['text', 'text-summary', 'lcov'],
  coverageThreshold: {
    global: {
      branches: 95,
      functions: 95,
      lines: 95,
      statements: 95,
    },
  },
}
