/** @type {import('jest').Config} */
module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  roots: ['<rootDir>/test'],
  testMatch: ['<rootDir>/test/**/*.test.ts'],
  transform: {
    '^.+\\.(t|j)s$': [
      'ts-jest',
      {
        tsconfig: '<rootDir>/tsconfig.spec.json',
      },
    ],
  },
  testEnvironment: 'node',
  clearMocks: true,
  coverageProvider: 'v8',
  collectCoverage: true,
  collectCoverageFrom: [
    '<rootDir>/src/configuration/validators/assert-jira-triage-runtime-ready.ts',
    '<rootDir>/src/configuration/validators/assert-repository-review-runtime-ready.ts',
    '<rootDir>/src/configuration/loaders/load-node-env-files.ts',
    '<rootDir>/src/configuration/loaders/node-configuration-loader.ts',
    '<rootDir>/src/configuration/error/error.ts',
    '<rootDir>/src/configuration/mapper/node-configuration.mapper.ts',
    '<rootDir>/src/configuration/validators/node-configuration.validator.ts',
    '<rootDir>/src/configuration/loaders/toml-loader.ts',
    '<rootDir>/src/configuration/schemas/**/*.ts',
    '<rootDir>/src/configuration/utilities/deep-freeze.ts',
    '<rootDir>/src/agent/provider/node-agent-llm-resolver.ts',
    '<rootDir>/src/agent/provider/error/error.ts',
    '<rootDir>/src/agent/agent.module.ts',
    '<rootDir>/src/error/error.ts',
    '<rootDir>/src/agent/agent-process-resolver.ts',
    '<rootDir>/src/handlers/jira-triage/classifier/jira-triage-classifier.ts',
    '<rootDir>/src/handlers/jira-triage/escalator/jira-triage-escalator.ts',
    '<rootDir>/src/handlers/jira-triage/error/error.ts',
    '<rootDir>/src/handlers/jira-triage/mapper/jira-triage-classification-mapper.ts',
    '<rootDir>/src/handlers/jira-triage/composer/jira-triage-prompt-composer.ts',
    '<rootDir>/src/handlers/jira-triage/fix/jira-triage-fix-attempter.ts',
    '<rootDir>/src/handlers/jira-triage/repro/jira-triage-repro-attempter.ts',
    '<rootDir>/src/handlers/jira-triage/resolver/jira-repo-resolver.ts',
    '<rootDir>/src/handlers/jira-triage/resolver/resolve-allowlisted-suites.ts',
    '<rootDir>/src/handlers/jira-triage/runner/is-unrunnable-suite-failure.ts',
    '<rootDir>/src/handlers/jira-triage/runner/test-runner.ts',
    '<rootDir>/src/handlers/repository-review/composer/repository-review-guideline-loader.ts',
    '<rootDir>/src/handlers/repository-review/composer/repository-review-prompt-composer.ts',
    '<rootDir>/src/handlers/repository-review/mapper/repository-review-comment-formatter.ts',
    '<rootDir>/src/handlers/repository-review/mapper/repository-review-result-mapper.ts',
    '<rootDir>/src/execution/handler/execution-job-handler-registry.ts',
    '<rootDir>/src/execution/handler/error/error.ts',
    '<rootDir>/src/execution/jobs/processing/execution-job-failure-mapper.ts',
    '<rootDir>/src/execution/jobs/processing/execution-job-processor.ts',
    '<rootDir>/src/execution/jobs/polling/execution-job-poller.ts',
    '<rootDir>/src/execution-engine/cursor/cursor-execution-error.ts',
    '<rootDir>/src/cortex/cortex-client.ts',
    '<rootDir>/src/cortex/cortex-request.ts',
    '<rootDir>/src/cortex/resources/execution-job/cortex-execution-job-resource.ts',
    '<rootDir>/src/cortex/resources/execution-job/error/error.ts',
    '<rootDir>/src/cortex/resources/node/cortex-node-resource.ts',
    '<rootDir>/src/cortex/resources/node/error/error.ts',
    '<rootDir>/src/node/node-descriptor.provider.ts',
    '<rootDir>/src/workspace/git-workspace-manager.ts',
  ],

  coverageDirectory: '<rootDir>/coverage',
  coverageReporters: ['text', 'text-summary', 'lcov'],
  coverageThreshold: {
    global: {
      branches: 94,
      functions: 95,
      lines: 95,
      statements: 95,
    },
  },
}
