// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import path from 'path';
import { defineConfig } from 'prisma/config';

const databaseDirectory = path.resolve(__dirname);
const apiRoot = path.resolve(__dirname, '../../..');
const monorepoRoot = path.resolve(apiRoot, '../..');

dotenv.config({ path: path.join(monorepoRoot, 'env/.env.development') });

export default defineConfig({
  schema: path.join(databaseDirectory, 'prisma/schema.prisma'),
  migrations: {
    path: path.join(databaseDirectory, 'prisma/migrations'),
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
