// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import path from 'path';
import { defineConfig } from 'prisma/config';

const directoryName = path.resolve(__dirname, '../../..');

dotenv.config({ path: path.join(directoryName, 'env/.env.development') });

export default defineConfig({
  schema: 'src/infraestructure/database/prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
