// Copyright (c) 2026, PinkTech
// https://pink-tech.io/

import type { Content } from '../content'
import type { TokenUsage } from '../usage/token-usage'
import type { LLMStopReason } from '../stop-reason/llm-stop-reason'

/**
 * Represents the normalized outcome of a non-streaming
 * {@link LLM.complete} request.
 *
 * Provider adapters map vendor-specific completion payloads into this shape so
 * callers can consume assistant content, stop reason, model information, and
 * token usage without depending on provider-specific APIs.
 */
export interface LLMResponse {
  /**
   * Content generated by the language model.
   *
   * A response commonly contains {@link TextContent},
   * {@link ToolUseContent}, or a combination of both. Consumers should inspect
   * each block's `type` instead of assuming the response contains a single text
   * value.
   */
  readonly content: readonly Content[]

  /**
   * Model that produced the response.
   *
   * This value may differ from the requested model when the provider resolves
   * an alias or routes the request to a concrete model snapshot.
   */
  readonly model: string

  /**
   * Provider-assigned completion identifier, when available.
   *
   * This value can be used for logging, tracing, and correlating provider
   * requests. It must not be treated as a Cortex execution, job, or agent
   * identifier.
   */
  readonly providerResponseId?: string

  /**
   * Normalized reason the language model stopped generating the response.
   *
   * Provider adapters convert vendor-specific values, such as `stop`,
   * `length`, or `tool_calls`, into a provider-independent
   * {@link LLMStopReason}.
   */
  readonly stopReason: LLMStopReason

  /**
   * Token usage reported for this completion.
   *
   * Contains the normalized input and output token counts returned by the
   * provider. A provider adapter may use zero when usage information is not
   * available.
   */
  readonly usage: TokenUsage
}
